# Generated by Django 3.1.7 on 2021-03-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_brand_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size5',
        ),
        migrations.AddField(
            model_name='product',
            name='blue',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='green',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='grey',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='l',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='m',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='red',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='s',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='xl',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='xxl',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='yellow',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
