# Generated by Django 3.1.7 on 2021-03-25 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20210324_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='blue',
            new_name='black',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='grey',
            new_name='pink',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='yellow',
            new_name='white',
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainApp.seller'),
            preserve_default=False,
        ),
    ]
