# Generated by Django 3.1.7 on 2021-03-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20210325_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=28)),
                ('uname', models.CharField(max_length=28)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=28, null=True)),
                ('address1', models.CharField(blank=True, default=None, max_length=28, null=True)),
                ('address2', models.CharField(blank=True, default=None, max_length=28, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=28, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=28, null=True)),
                ('pin', models.CharField(blank=True, default=None, max_length=28, null=True)),
            ],
        ),
    ]
